In [1]:
import torch

In [3]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [7]:
b = torch.tensor([[1,2,3],[4,5,6]])
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
zeros  = torch.zeros([3,4])
ones = torch.ones(2,2,3)
rand = torch.rand(3,3)
randn = torch.randn(3,3)

In [18]:
x = torch.rand(2,3,4)

x.shape, x.size(), x.dim()

(torch.Size([2, 3, 4]), torch.Size([2, 3, 4]), 3)

In [21]:
y = x.view(6,4)
y = x.reshape(6, 4) 

In [23]:
x = torch.rand(3, 4)
x

tensor([[0.6699, 0.0791, 0.3302, 0.0463],
        [0.6947, 0.6118, 0.7816, 0.1623],
        [0.2472, 0.7928, 0.3568, 0.6622]])

In [25]:
row_sums = x.sum(dim=1)
row_sums

tensor([1.1256, 2.2505, 2.0589])

In [27]:
col_sums = x.sum(dim=0) 
col_sums

tensor([1.6118, 1.4838, 1.4687, 0.8708])

In [28]:
keep_dim = x.sum(dim=1, keepdim=True) 
keep_dim

tensor([[1.1256],
        [2.2505],
        [2.0589]])

In [29]:
x = torch.rand(5, 6)

In [31]:
a = x[0]  # First row

In [32]:
x = torch.rand(5, 6)